### ISSUE TITLE
NixOS package not working

### ISSUE THREAD

**Issue by Peter015** [rharish101/ReGreet#12]
When I try to run ReGreet under NixOS I get the error 
```
ERROR: Couldn't create log file '/var/log/regreet/log': Permission denied (os error 13)
thread 'main' panicked at 'Couldn't initialize greetd client: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/gui/model.rs:78:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I think (but I am not sure) that this is due to NixOS having a read only filesystem.

**Comment by Peter015** [comment]
I found the solution to be   systemd.tmpfiles.rules = [
    "d /var/log/regreet 0755 greeter greeter - -"
    "d /var/cache/regreet 0755 greeter greeter - -"
  ];

**Comment by Peter015** [comment]
Thank you for creating this software

**Comment by Peter015** [comment]
With this config:
```
    greetd = {
      enable = true;
      settings = {
        default_session = {
          command = "${pkgs.cage}/bin/cage -s -- ${pkgs.greetd.regreet}/bin/regreet";
          user = "greeter";
        };
      };
    };
  environment.etc."greetd/regreet.toml".text = ''
  background = "/home/peterz/Pictures/Wallpapers/greeter/20459081.jpg"
  background_fit = "Contain"

  [GTK]
  # Whether to use the dark theme
  application_prefer_dark_theme = true

  # Font name and size
  font_name = "Victor Mono SemiBold 16"
  
  # GTK theme name
  theme_name = "SolArc-Darker"
  '';

  systemd.tmpfiles.rules = [
    "d /var/log/regreet 0755 greeter greeter - -"
    "d /var/cache/regreet 0755 greeter greeter - -"
  ];
```
It does not work. When I try to run it from the CLI it errors as 
```
ERROR: Couldn't create log file '/var/log/regreet/log': Permission denied (os error 13)
thread 'main' panicked at 'Couldn't initialize greetd client: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/gui/model.rs:78:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
And when running on boot I am dropped into a blank screen.
